<a href="https://colab.research.google.com/github/riyan518z/paatshala/blob/main/worknumpy%26panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np
xy = np.arange(10,50)
yx = xy.reshape((4,10))
print(xy)
print(yx)
xx = yx[:, -1]
xx

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([19, 29, 39, 49])

In [ ]:
#2
n = np.full((3,3),5)
print(n)
p = np.arange(1,10).reshape((3,3))
print(p)
mul = n * p
print(mul)
t = np.transpose(mul)
print(t)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [ ]:
#3
import random
ra = np.random.randint(10, 101, size=15)
u = np.where(ra > 50, -1, ra)
c = np.sum(u == -1)

print(ra)
print(u)
print(c)

[68 57 50 27 28 37 86 81 93 45 30 87 84 59 80]
[-1 -1 50 27 28 37 -1 -1 -1 45 30 -1 -1 -1 -1]
9


In [ ]:
#4
arr = np.random.rand(5, 4)
max_row_index = np.argmax(np.sum(arr, axis=1))

row_min = arr.min(axis=1, keepdims=True)
row_max = arr.max(axis=1, keepdims=True)
normalized = (arr - row_min) / (row_max - row_min)

print("\n4. Random 5x4 Array:\n", arr)
print("Index of Row with Max Sum:", max_row_index)
print("Normalized Array:\n", normalized)


4. Random 5x4 Array:
 [[0.69848891 0.26912997 0.65796713 0.69994043]
 [0.32850873 0.01057035 0.92235042 0.34715062]
 [0.93150685 0.00139215 0.27907848 0.40293108]
 [0.01435325 0.9204962  0.65979344 0.80349577]
 [0.41346469 0.64185142 0.48119752 0.75113432]]
Index of Row with Max Sum: 3
Normalized Array:
 [[0.99663074 0.         0.90257131 1.        ]
 [0.34870073 0.         1.         0.36914634]
 [1.         0.         0.29855063 0.43170905]
 [0.         1.         0.712294   0.87088083]
 [0.         0.67636149 0.20058905 1.        ]]


In [ ]:
#5
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique = np.unique(arr)

counts = np.bincount(arr)
duplicates = np.where(counts > 1)[0]

print("\n Original Array:\n", arr)
print("Unique Elements:\n", unique)
print("Duplicates:\n", duplicates)


 Original Array:
 [1 3 5 3 7 9 1 5 5]
Unique Elements:
 [1 3 5 7 9]
Duplicates:
 [1 3 5]


In [ ]:
#6
arr = np.arange(1, 37).reshape(6, 6)
sub = arr[1:5, 1:5]
e = sub[sub % 2 == 0]

print("\n6. Original 6x6 Array:\n", arr)
print("Middle 4x4 Submatrix:\n", sub)
print("Even Numbers in Submatrix:\n", e)


6. Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even Numbers in Submatrix:
 [ 8 10 14 16 20 22 26 28]


In [ ]:
#7
arr = np.arange(12).reshape(3, 4)
re = arr.reshape(2, 6)
f = re.flatten()
reshaped_again = f.reshape(4, 3)

print("\n7. Original 3x4 Array:\n", arr)
print("Reshaped to 2x6:\n", re)
print("Flattened to 1D:\n", f)
print("Reshaped to 4x3:\n", reshaped_again)


7. Original 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened to 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#8
a = np.array([[1, 2], [3, 4]])
newr = np.vstack([a, [[5, 6]]])
newc = np.hstack([newr, [[7], [8], [9]]])

print(f'array a:\n{a}\n')
print(f'array after appending row:\n{newr}\n')
print(f'array after appending row and column:\n{newc}')

array a:
[[1 2]
 [3 4]]

array after appending row:
[[1 2]
 [3 4]
 [5 6]]

array after appending row and column:
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
#9
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.concatenate([a, b, c])
e = d.reshape((3, 3))
f = np.diag(e)

print(f'array a:\n{a}\n')
print(f'array b:\n{b}\n')
print(f'array c:\n{c}\n')
print(f'joined single array d:\n{d}\n')
print(f'reshaped 3X3 array e:\n{e}\n')
print(f'extracted diagonal elements are:\n{f}')

array a:
[1 2 3]

array b:
[4 5 6]

array c:
[7 8 9]

joined single array d:
[1 2 3 4 5 6 7 8 9]

reshaped 3X3 array e:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

extracted diagonal elements are:
[1 5 9]


In [ ]:
#10
arr = np.arange(1, 21)
filtered = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = filtered.size

print("\n Original Array:\n", arr)
print("Values Divisible by 3 or 5:\n", filtered)
print("Count:", count)


 Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Values Divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]
Count: 9


pandas

In [41]:
#1
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head(11)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   

      who  adult_male deck  embark_town alive  alone  
0     man        True  NaN  Southampton    no  False  
1   woman       False    C    Cherbourg   yes  False  
2   woman       False  NaN  Southampton   yes   True  
3   woman       False    C  Southampton   yes  False  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
6     man        True    E  Southampton    no   True  
7   child       False  NaN  Southampton    no  False  
8   woman       False  NaN  Southampton   yes  False  
9   child       False  NaN    Cherbourg   yes  False  
10  child       False    G  Southampton   yes  False

In [42]:
#2
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [46]:
#3
p = titanic.groupby('sex')['survived'].mean() * 100
p

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [47]:
#4
age = titanic['age']
mean = age.mean()
median = age.median()
mode= age.mode().tolist()
std = age.std()

print(f'Average passenger age: {mean}')
print(f'Median passenger age: {median}')
print(f'Mode passenger age: {mode}')
print(f'passenger age standard-deviation: {std}')

Average passenger age: 29.69911764705882
Median passenger age: 28.0
Mode passenger age: [24.0]
passenger age standard-deviation: 14.526497332334044


In [ ]:
#5
titanic['pclass'].value_counts().sort_index()

pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [ ]:
#6
titanic[(titanic['sex'] == 'female') & (titanic['age'] < 18) & (titanic['survived'] == 1)]

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

In [49]:
#7
median_age = titanic['age'].median()
titanic['age'].fillna(median_age, inplace=True)


In [52]:
#8
conditions = [titanic['age'] < 18, (titanic['age'] >= 18) & (titanic['age'] < 60), titanic['age']>60]
values = ['Child','Adult', 'Senior']
titanic['age_group'] = np.select(conditions, values, default='Unknown')
titanic.head(10)


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male  28.0      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult  
5    man        True  NaN   Queenstown    no   True     Adult  
6    man        True    E  Southampton    no   True     Adult  
7  child       False  NaN  Southampton    no  False     Child  
8  woman       False  NaN  Southampton   yes  False     Adult  
9  child       False  NaN    Cherbourg   yes  False     Child

In [53]:
titanic['age_group'] = np.where(titanic['age'] < 18, 'Child', np.where(titanic['age'] <= 60, 'Adult', 'Senior'))
def classify_age(age):
  if age < 18:
    return 'Child'
  elif age <= 60:
    return 'Adult'
  else:
    return 'Senior'

  titanic['age_group'] = titanic['age'].apply(classify_age)

In [54]:
#9
titanic.sort_values('fare', ascending=False).head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

In [55]:
#10
titanic.groupby(['pclass', 'sex'])['fare'].mean().round(2)

pclass  sex   
1       female    106.13
        male       67.23
2       female     21.97
        male       19.74
3       female     16.12
        male       12.66
Name: fare, dtype: float64

In [56]:
#11
titanic.rename(columns = {'sex': 'gender', 'fare':'ticket_fare'}, inplace=True)
titanic.head()

survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  class  \
0         0       3    male  22.0      1      0       7.2500        S  Third   
1         1       1  female  38.0      1      0      71.2833        C  First   
2         1       3  female  26.0      0      0       7.9250        S  Third   
3         1       1  female  35.0      1      0      53.1000        S  First   
4         0       3    male  35.0      0      0       8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult

In [57]:
#12
titanic.groupby(['pclass','survived']).size()

pclass  survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64

In [58]:
#13
titanic.groupby(['pclass', 'gender'])['age'].mean()

pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64